### ISSUE TITLE
0.7.0 update bricked my home automation system (GPIO subsys) - how do I rollback / turn off auto updates?

### ISSUE THREAD

**Issue by gtbrons** [WebThingsIO/gpio-adapter#34]
2019-09-21 00:02:49.195 INFO   : Checking for add-on updates...
2019-09-21 00:02:49.426 INFO   : Unloading GpioAdapter
2019-09-21 00:02:49.431 INFO   : gpio: Adapter: GpioAdapter unloaded
2019-09-21 00:02:52.939 INFO   : Fetching add-on https://s3-us-west-2.amazonaws.com/mozilla-gateway-addons/gpio-adapter-0.7.0-linux-arm-v8.tgz as /tmp/FObcDf/gpio-adapter.tar.gz
2019-09-21 00:02:53.431 INFO   : Expanding add-on /tmp/FObcDf/gpio-adapter.tar.gz into /home/pi/.mozilla-iot/addons/gpio-adapter
2019-09-21 00:02:53.850 INFO   : Loading add-on: gpio-adapter
2019-09-21 00:02:53.894 INFO   : Finished updating add-ons
2019-09-21 00:02:54.647 INFO   : gpio: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2019-09-21 00:02:54.694 INFO   : gpio: Loading add-on for gpio-adapter from /home/pi/.mozilla-iot/addons/gpio-adapter
2019-09-21 00:02:55.029 ERROR  : gpio: { Error: EINVAL: invalid argument, write
2019-09-21 00:02:55.030 ERROR  : gpio:     at Object.fs.writeSync (fs.js:735:20)
2019-09-21 00:02:55.033 ERROR  : gpio:     at Object.fs.writeFileSync (fs.js:1309:24)
2019-09-21 00:02:55.035 ERROR  : gpio:     at exportGpio (/home/pi/.mozilla-iot/addons/gpio-adapter/node_modules/onoff/onoff.js:18:8)
2019-09-21 00:02:55.037 ERROR  : gpio:     at new Gpio (/home/pi/.mozilla-iot/addons/gpio-adapter/node_modules/onoff/onoff.js:172:36)
2019-09-21 00:02:55.040 ERROR  : gpio:     at new GpioDevice (/home/pi/.mozilla-iot/addons/gpio-adapter/gpio-adapter.js:108:19)
2019-09-21 00:02:55.042 ERROR  : gpio:     at GpioAdapter.db.open.then.then (/home/pi/.mozilla-iot/addons/gpio-adapter/gpio-adapter.js:231:9)
2019-09-21 00:02:55.044 ERROR  : gpio:     at <anonymous> errno: -22, code: 'EINVAL', syscall: 'write' }

**Comment by mrstegeman** [comment]
@dhylands Do you have any devices you can test this with?

**Comment by mrstegeman** [comment]
@gtbrons Apologies for that! Things should be fixed now in 0.7.1.

**Comment by gtbrons** [comment]
Thanks! @mrstegeman  Everything's back to normal with 0.7.1
